### ISSUE TITLE
Needs Updates

### ISSUE THREAD

**Issue by BatteryVoltic** [skarab42/ValheimTwitch#29]
Is there by any chance we can get this mod updated on the Thunderstore/R2ModMan for the Hearth and Home Update. Ever since the update dropped this mod has stopped working.

**Comment by Joybrther** [comment]
And with the new update that just came out a few days ago if possible whenever have time of course

**Comment by Kr33pa** [comment]
Cant suggest this, doesn't work. update it and I will change review.

**Comment by TheRedTrashPanda** [comment]
This still isn't working for Thunderstone, but works for Nexus...why?

**Comment by skarab42** [comment]
Sorry this mod is not maintained anymore, I don't have time to work on it.
