### ISSUE TITLE
Reward inaccessible si limitations

### ISSUE THREAD

**Issue by j-wiedemann** [skarab42/ValheimTwitch#3]
Les rewards sont inaccessibles si le streamer défini des limitations.
Ex de limites : https://zupimages.net/up/21/13/ylv4.jpg
Ex du message d'erreur : https://zupimages.net/up/21/13/tpdd.jpg

Selon @Hideoo le problème est :
Je pense que ça doit venir de "should_redemptions_skip_request_queue" qui est pas à true
Du coup les rewards s'entassent en unfulfilled et du coup, on est toujours hors limite vu qu'il prend en compte eux dans la queue

**Comment by skarab42** [comment]
Probablement lier a #4 je ne check pas le status du reward...

**Comment by skarab42** [comment]
Visiblement c'est uniquement si tu a le combo restriction de temps + auto validation DESACTIVE.
Merci de confirmer.

**Comment by skarab42** [comment]
C'est pas vraiment un bug, mais plutôt une mauvaise configuration des points de chaîne. J'ai forcer l'auto-fullfill a la création et j'ajouterais une note dans la docs pour expliquer qu'il ne faut pas désactiver cet feature si tu veux des restrictions.
