### ISSUE TITLE
Does not work with thunderstore mod manager

### ISSUE THREAD

**Issue by TheRedTrashPanda** [skarab42/ValheimTwitch#34]
### Describe the bug

Valheim Twitch does not work when downloaded from & launched with Thunderstore. Is there any way you can update the coding so it works? Apparently Nexus Mods works but it doesn't on Thunderstore & I'd really hate to have to switch mod managers once again just to get this one working. Thank you!

### Reproduction

IDK

### System Info

```Shell
Windows 10
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by skarab42** [comment]
Sorry this mod is not maintained anymore, I don't have time to work on it.
